sudo: false
language: scala
scala:
  - 2.11.5
jdk:
  - oraclejdk8
  - oraclejdk7
services:
  - memcached
  - redis
script: 
  - cd issue28 && sbt run
  - sbt ++2.11.5 coverage test 
  - sbt ++2.11.2 test
  - sbt ++2.11.0 test
after_success: "sbt coverageAggregate coveralls"
